#
# @file    .travis.yml
# @brief   Travis CI configuration file for MOCCASIN
# @author  Harold Gomez
# @author  Michael Hucka
#
# This software is part of MOCCASIN, the Model ODE Converter for Creating
# Automated SBML INteroperability. Visit https://github.com/sbmlteam/moccasin/.

language: python

python:
    - "2.7"

cache:
    # Based on https://docs.travis-ci.com/user/caching/, the default is 3 min.
    # Set it to 2 hrs because our py.test tests take a very long time.
    timeout: 7200
    apt: true
    pip: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libxml2-dev
            - libz-dev
            - libbz2-dev

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

virtualenv:
    system_site_packages: true

# before_install:
#     - sudo wget http://download.opensuse.org/repositories/home:fbergman:libsbml/xUbuntu_14.04/Release.key
#     - sudo apt-key add - < Release.key  
#     - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/fbergman:/libsbml/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/python-libsbml.list"
#     - sudo apt-key update
#     - sudo apt-get update -qq
#     - sudo apt-get install -y libxml2-dev
#     - sudo apt-get install -y libz-dev
#     - sudo apt-get install -y libbz2-dev
#     - sudo apt-get install -y --force-yes python-libsbml

install: 
    - pip install -r requirements.txt --use-mirrors --download-cache "$HOME/.cache"
    - pip install python-libsbml
    - pip install coverage
    - pip install coveralls

env:
    - TEST_CASES=tests/converter_test
    - TEST_CASES=tests/evaluate_test
    - TEST_CASES=tests/syntax_test

script: 
    - coverage run setup.py test -t $TEST_CASES

after_success:
    coveralls
